#### Import Necessary Libraries

In [ ]:
import pandas as pd

#### Extraction Layer

In [2]:
ziko_df = pd.read_csv('ziko_logistics_data.csv')

In [3]:
ziko_df.head()

,Transaction_ID,Date,Customer_ID,Product_ID,Quantity,Unit_Price,Total_Cost,Discount_Rate,Sales_Channel,Order_Priority,...,Return_Reason,Payment_Type,Taxable,Region,Country,Customer_Name,Customer_Phone,Customer_Email,Customer_Address,Product_List_Title
0,200,2020-01-01 20:32:25.945945945,1086,536,3,120.436821,8265.374549,0.20,Online,High,...,Wrong Item,Wire Transfer,False,West,Canada,Customer 200,+1-652-572-9306,customer.200.78@example.com,"275 Second St, Phoenix, USA",Product 53
1,321,2020-01-02 06:55:08.108108108,1078,523,6,475.724994,4047.850479,NaN,Reseller,Critical,...,Damaged,PayPal,True,South,Mexico,Customer 321,+1-311-186-5760,customer.321.13@sample.com,"478 Third St, New York, USA",Product 33
2,989,2020-01-06 08:12:58.378378378,1077,535,3,146.400556,NaN,0.05,Direct,Critical,...,Damaged,PayPal,True,West,Canada,Customer 989,+1-922-606-9032,customer.989.99@example.com,"843 Second St, Phoenix, USA",Product 6
3,682,2020-01-07 22:03:14.594594594,1027,546,6,19.373194,8194.281993,NaN,Reseller,Medium,...,Wrong Item,Cash,True,South,Canada,Customer 682,+1-237-853-5808,customer.682.66@demo.com,"153 Main St, Phoenix, USA",Product 68
4,484,2020-01-07 07:08:06.486486486,1052,556,8,193.221313,8331.329249,0.20,Direct,Low,...,Late,Cash,False,South,Mexico,Customer 484,+1-986-360-9109,customer.484.3@sample.com,"264 Second St, New York, USA",Product 89

In [5]:
# To get the summary statistics of the DataFrame
ziko_df.describe()

,Transaction_ID,Customer_ID,Product_ID,Quantity,Unit_Price,Total_Cost,Discount_Rate
count,1005.000000,1005.000000,1005.000000,1005.000000,904.000000,905.000000,714.000000
mean,499.057711,1050.042786,529.886567,4.972139,256.467791,5096.553818,0.122479
std,288.867556,29.281420,17.192288,2.555991,142.409717,2688.542137,0.055316
min,1.000000,1001.000000,501.000000,1.000000,10.005701,500.291829,0.050000
25%,248.000000,1025.000000,515.000000,3.000000,134.082539,2727.043200,0.100000
50%,498.000000,1050.000000,530.000000,5.000000,258.425121,5046.019514,0.100000
75%,749.000000,1075.000000,544.000000,7.000000,378.059382,7383.683725,0.150000
max,1000.000000,1100.000000,560.000000,9.000000,499.457380,9966.999934,0.200000

In [6]:
ziko_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1005 entries, 0 to 1004
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         1005 non-null   int64
 1   Date                   1005 non-null   str
 2   Customer_ID            1005 non-null   int64
 3   Product_ID             1005 non-null   int64
 4   Quantity               1005 non-null   int64
 5   Unit_Price             904 non-null    float64
 6   Total_Cost             905 non-null    float64
 7   Discount_Rate          714 non-null    float64
 8   Sales_Channel          1005 non-null   str
 9   Order_Priority         1005 non-null   str
 10  Warehouse_Code         1005 non-null   str
 11  Ship_Mode              1005 non-null   str
 12  Delivery_Status        1005 non-null   str
 13  Customer_Satisfaction  1005 non-null   str
 14  Item_Returned          1005 non-null   bool
 15  Return_Reason          904 non-null    str
 16  Payment_Type           1005 non-null   str
 17  Taxable                1005 non-null   bool
 18  Region                 1005 non-null   str
 19  Country                1005 non-null   str
 20  Customer_Name          1005 non-null   str
 21  Customer_Phone         1005 non-null   str
 22  Customer_Email         1005 non-null   str
 23  Customer_Address       1005 non-null   str
 24  Product_List_Title     1005 non-null   str
dtypes: bool(2), float64(3), int64(4), str(16)
memory usage: 182.7 KB

In [7]:
ziko_df.columns

Index(['Transaction_ID', 'Date', 'Customer_ID', 'Product_ID', 'Quantity',
       'Unit_Price', 'Total_Cost', 'Discount_Rate', 'Sales_Channel',
       'Order_Priority', 'Warehouse_Code', 'Ship_Mode', 'Delivery_Status',
       'Customer_Satisfaction', 'Item_Returned', 'Return_Reason',
       'Payment_Type', 'Taxable', 'Region', 'Country', 'Customer_Name',
       'Customer_Phone', 'Customer_Email', 'Customer_Address',
       'Product_List_Title'],
      dtype='str')